// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktbdyngkwivznapizgan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0YmR5bmdrd2l2em5hcGl6Z2FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzExODQsImV4cCI6MjA2NTkwNzE4NH0.TAJIx3XqI1XzghnbsBOCh9Mr-BCqC6vNuRrhGQmQ3Rs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);